apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: hacwa-aws-secrets
            key: access-key
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: hacwa-aws-secrets
            key: secret-access-key
            namespace: external-secrets
