apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic

  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: proxmox-csi-plugin
    creationPolicy: Owner
    deletionPolicy: Retain

    template:
      type: Opaque
      engineVersion: v2
      mergePolicy: Replace
      data:
        config.yaml: |
          clusters:
            - url: https://10.0.4.2:8006/api2/json
              insecure: true
              token_id: "kubernetes-csi@pve!csi"
              token_secret: "{{ .tokenSecret }}"
              region: eu-west-2

  data:
    - secretKey: tokenSecret
      remoteRef:
        key: hacwa_aws_secrets
        property: proxmox-csi-token-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
