apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: wastebin-runtime-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  length: 96
  digits: 16
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - signing-key
    - password-salt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wastebin-runtime-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce

  target:
    name: wastebin-runtime-secrets
    creationPolicy: Owner
    deletionPolicy: Retain

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: wastebin-runtime-secrets
