apiVersion: v1
kind: Service
metadata:
  name: element
  namespace: matrix
  labels:
    app.kubernetes.io/name: element
    app.kubernetes.io/part-of: matrix
spec:
  selector:
    app.kubernetes.io/name: element
    app.kubernetes.io/part-of: matrix
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: element
  namespace: matrix
  labels:
    app.kubernetes.io/name: element
    app.kubernetes.io/part-of: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: element
      app.kubernetes.io/part-of: matrix
  template:
    metadata:
      labels:
        app.kubernetes.io/name: element
        app.kubernetes.io/part-of: matrix
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30

      containers:
        - name: element
          image: vectorim/element-web:v1.12.11
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /app/config.json
              subPath: config.json
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: matrix-element-config
