apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - synapse.yaml
  - mas.yaml

configMapGenerator:
  - name: matrix-synapse-config
    files:
      - render.py=tools/render.py
      - homeserver.yaml.template=config/homeserver.yaml.template
      - log.config=config/log.config

  - name: matrix-mas-config
    files:
      - render-mas.py=tools/render-mas.py
      - mas-config.yaml.template=config/mas-config.yaml.template
