apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - synapse.yaml

configMapGenerator:
  - name: matrix-synapse-config
    files:
      - render.py=tools/render.py
      - homeserver.yaml.template=config/homeserver.yaml.template
      - log.config=config/log.config
