apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - synapse.yaml
  - mas.yaml
  - element.yaml
  - livekit.yaml
  - rtc-auth.yaml

configMapGenerator:
  - name: matrix-synapse-config
    files:
      - render.py=tools/render.py
      - homeserver.yaml.template=config/homeserver.yaml.template
      - log.config=config/log.config

  - name: matrix-mas-config
    files:
      - render-mas.py=tools/render-mas.py
      - mas-config.yaml.template=config/mas-config.yaml.template

  - name: matrix-element-config
    files:
      - config.json=config/element-config.json

  - name: matrix-livekit-config
    files:
      - render.py=tools/render.py
      - livekit.yaml.template=config/livekit.yaml.template
