apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: matrix-public-routes
  namespace: matrix
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: external-services
  to:
    - group: ""
      kind: Service
      name: element
    - group: ""
      kind: Service
      name: mas
    - group: ""
      kind: Service
      name: synapse
    - group: ""
      kind: Service
      name: matrix-rtc-auth
    - group: ""
      kind: Service
      name: livekit
