apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgresql-service.yaml
  - postgresql-statefulset.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - servicemonitor.yaml
  - probe.yaml

configMapGenerator:
  - name: keycloak-grafana-dashboard
    namespace: monitoring
    files:
      - keycloak.json=dashboard.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
