apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: zabbix
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: zabbix-web
spec:
  selector:
    app.kubernetes.io/name: zabbix-web

  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: zabbix
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: zabbix-web
spec:
  replicas: 0

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/name: zabbix-web

  template:
    metadata:
      labels:
        app.kubernetes.io/name: zabbix-web

    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 60

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: zabbix-web
          image: docker.io/zabbix/zabbix-web-nginx-pgsql:7.4.7-ubuntu
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          env:
            - name: ZBX_SERVER_HOST
              value: zabbix-server

            - name: ZBX_SERVER_PORT
              value: "10051"

            - name: DB_SERVER_HOST
              value: zabbix-postgresql

            - name: DB_SERVER_PORT
              value: "5432"

            - name: POSTGRES_DB
              value: zabbixdb

            - name: POSTGRES_USER
              value: zabbix

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-postgresql-auth
                  key: postgres-password

            - name: PHP_TZ
              value: Europe/London

            - name: ZBX_SERVER_NAME
              value: HACWA Zabbix

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 120

          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6

          resources:
            requests:
              cpu: 100m
              memory: 256Mi

            limits:
              cpu: "1"
              memory: 1Gi
