apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: hacwa-elasticsearch-tls
  namespace: elastic-stack
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: elastic-stack
spec:
  endpoints:
    - fqdn:
        hostname: hacwa-es-http.elastic-stack.svc.cluster.local
        port: 9200
  tls:
    insecureSkipVerify: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kibana-external
  namespace: elastic-stack
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/part-of: elastic-stack
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external-gateway
      namespace: platform-gateway
      sectionName: https
  hostnames:
    - elk.hacwa.co.uk
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: hacwa-kb-http
          namespace: elastic-stack
          port: 5601
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fleet-server-external
  namespace: elastic-stack
  labels:
    app.kubernetes.io/name: fleet-server
    app.kubernetes.io/part-of: elastic-stack
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external-gateway
      namespace: platform-gateway
      sectionName: https
  hostnames:
    - fleet.hacwa.co.uk
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: fleet-server-agent-http
          namespace: elastic-stack
          port: 8220
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: elasticsearch-external
  namespace: elastic-stack
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: elastic-stack
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external-gateway
      namespace: platform-gateway
      sectionName: https
  hostnames:
    - elasticsearch.hacwa.co.uk
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: hacwa-elasticsearch-tls
          namespace: elastic-stack
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: apm-server-external
  namespace: elastic-stack
  labels:
    app.kubernetes.io/name: apm-server
    app.kubernetes.io/part-of: elastic-stack
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external-gateway
      namespace: platform-gateway
      sectionName: https
  hostnames:
    - apm.hacwa.co.uk
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: hacwa-apm-http
          namespace: elastic-stack
          port: 8200
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: logstash-syslog-external
  namespace: elastic-stack
  labels:
    app.kubernetes.io/name: logstash-syslog
    app.kubernetes.io/part-of: elastic-stack
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external-gateway
      namespace: platform-gateway
      sectionName: syslog-udp
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: hacwa-ls-syslog
          namespace: elastic-stack
          port: 5514
          weight: 1
