apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: external-gateway-proxy
  namespace: platform-gateway
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          metallb.io/address-pool: manual-pool
          metallb.io/loadBalancerIPs: 10.0.20.17
        patch:
          type: StrategicMerge
          value:
            spec:
              loadBalancerIP: 10.0.20.17
