apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  annotations:
    opencost.io/storage-hourly-cost: "0.0001271233"
    hacwa.co.uk/emulated-storage-tier: "aws-ebs-gp3"
    hacwa.co.uk/emulated-aws-region: "eu-west-2"
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.6.4
  share: /var/nfs/shared/k8s_sc8
  subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}/${pv.metadata.name}
  mountPermissions: "0777"
  onDelete: retain
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
mountOptions:
  - hard
  - timeo=600
  - retrans=2
