{{- if .Values.policy.resourcePolicy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ required "policy.resourcePolicy.name is required" .Values.policy.resourcePolicy.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: velero-policy
    app.kubernetes.io/part-of: velero
data:
  policies.yaml: |
    version: v1
    volumePolicies:
{{ toYaml .Values.policy.resourcePolicy.volumePolicies | indent 6 }}
{{- end }}
