apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: plex-external
  namespace: external-services
spec:
  endpoints:
    - ip:
        address: 10.0.0.120
        port: 32400
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: radarr-external
  namespace: external-services
spec:
  endpoints:
    - ip:
        address: 10.0.0.120
        port: 7876
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: sonarr-external
  namespace: external-services
spec:
  endpoints:
    - ip:
        address: 10.0.0.120
        port: 18989
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: sab-external
  namespace: external-services
spec:
  endpoints:
    - ip:
        address: 10.0.0.120
        port: 8088
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: request-external
  namespace: external-services
spec:
  endpoints:
    - ip:
        address: 10.0.0.120
        port: 5000
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: report-external
  namespace: external-services
spec:
  endpoints:
    - ip:
        address: 10.0.0.120
        port: 8181
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: radarr-4k-external
  namespace: external-services
spec:
  endpoints:
    - ip:
        address: 10.0.0.120
        port: 7807
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: sonarr-4k-external
  namespace: external-services
spec:
  endpoints:
    - ip:
        address: 10.0.0.120
        port: 8981
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: anime-external
  namespace: external-services
spec:
  endpoints:
    - ip:
        address: 10.0.0.120
        port: 8988
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: immich-external
  namespace: external-services
spec:
  endpoints:
    - ip:
        address: 10.0.0.101
        port: 2283
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: lidarr-external
  namespace: external-services
spec:
  endpoints:
    - ip:
        address: 10.0.0.120
        port: 8686
