apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefox-oauth2
  namespace: firefox
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: firefox-oauth2
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque

  data:
    - secretKey: client-secret
      remoteRef:
        key: hacwa_aws_secrets
        property: client-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: cookie-secret
      remoteRef:
        key: hacwa_aws_secrets
        property: cookie-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
