apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secret.yaml
  - pvc.yaml
  - firefox-deployment.yaml
  - firefox-service.yaml
  - oauth2-proxy-deployment.yaml
  - oauth2-proxy-service.yaml
  - httproute.yaml
  - servicemonitor.yaml
  - probe.yaml
  - dashboard.yaml
