apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: firefox-oauth2-proxy
  namespace: firefox
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/name: firefox
    app.kubernetes.io/component: oauth2-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: firefox
      app.kubernetes.io/component: oauth2-proxy

  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 15s
      scrapeTimeout: 10s
