apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheusrule.yaml

configMapGenerator:
  - name: gitlab-runner-grafana-dashboard
    namespace: monitoring
    files:
      - gitlab-runner.json=dashboard.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
