apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: holiday-countdown

resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml

configMapGenerator:
  - name: holiday-countdown-html
    files:
      - index.html=html/index.html
