apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-httproute.yaml
  - alertmanager-httproute.yaml
  - prometheus-httproute.yaml
  - etcd-scrapeconfig.yaml
  - nvidia-gpu-dashboard.yaml
  - nvidia-gpu-rules.yaml
