apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - proxmox-pve-scrapeconfig.yaml
  - proxmox-pve-rules.yaml
  - grafana-httproute.yaml
  - alertmanager-httproute.yaml
  - prometheus-httproute.yaml
  - etcd-scrapeconfig.yaml
  - nvidia-gpu-dashboard.yaml
  - nvidia-gpu-rules.yaml
  - ceph-csi-rules.yaml
  - ceph-csi-dashboard.yaml
  - platform-endpoint-probes.yaml
  - platform-endpoint-rules.yaml
  - platform-endpoint-dashboard.yaml
  - plex-dashboard.yaml

configMapGenerator:
  - name: ceph-grafana-dashboards
    namespace: monitoring
    files:
      - ceph-cluster.json=dashboards/ceph/ceph-cluster.json
      - ceph-osd-single.json=dashboards/ceph/ceph-osd-single.json
      - ceph-pools.json=dashboards/ceph/ceph-pools.json

  - name: proxmox-pve-grafana-dashboards
    namespace: monitoring
    files:
      - proxmox-overview.json=dashboards/proxmox/proxmox-overview.json
      - proxmox-nodes.json=dashboards/proxmox/proxmox-nodes.json
      - proxmox-guests.json=dashboards/proxmox/proxmox-guests.json
      - proxmox-storage.json=dashboards/proxmox/proxmox-storage.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
