apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: proxmox-pve
  namespace: monitoring
  labels:
    app.kubernetes.io/name: proxmox-pve-exporter
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  metricsPath: /pve
  scrapeInterval: 30s
  scrapeTimeout: 25s

  params:
    module:
      - default
    cluster:
      - "1"
    node:
      - "1"

  staticConfigs:
    - targets:
        - pve.hacwa.internal

  relabelings:
    - sourceLabels:
        - __address__
      targetLabel: __param_target

    - sourceLabels:
        - __param_target
      targetLabel: instance

    - targetLabel: __address__
      replacement: 10.0.0.227:9221

    - targetLabel: job
      replacement: proxmox-pve
