apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: proxmox-pve
  namespace: monitoring
  labels:
    app.kubernetes.io/name: proxmox-pve-exporter
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  scheme: HTTP
  metricsPath: /pve
  scrapeInterval: 30s
  scrapeTimeout: 25s
  honorTimestamps: true
  enableCompression: true

  params:
    module:
      - default
    cluster:
      - "1"
    node:
      - "1"

  staticConfigs:
    - targets:
        - pve.hacwa.internal

  relabelings:
    - action: Replace
      sourceLabels:
        - __address__
      separator: ";"
      regex: "(.*)"
      replacement: "$1"
      targetLabel: __param_target

    - action: Replace
      sourceLabels:
        - __param_target
      separator: ";"
      regex: "(.*)"
      replacement: "$1"
      targetLabel: instance

    - action: Replace
      separator: ";"
      regex: "(.*)"
      replacement: prometheus-pve-exporter.hacwa.internal:9221
      targetLabel: __address__

    - action: Replace
      separator: ";"
      regex: "(.*)"
      replacement: proxmox-pve
      targetLabel: job
