apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-prometheus-scrape
  namespace: external-services
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: minio-prometheus-scrape
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque

  data:
    - secretKey: token
      remoteRef:
        key: hacwa_aws_secrets
        property: minio-prometheus-token
