apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-smoke-test
  labels:
    app.kubernetes.io/name: tenant-smoke-test
    app.kubernetes.io/part-of: capsule-tenant-smoke-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tenant-smoke-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tenant-smoke-test
        app.kubernetes.io/part-of: capsule-tenant-smoke-test
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: smoke-test
          image: busybox:1.37.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - while true; do sleep 3600; done
          resources:
            requests:
              cpu: 5m
              memory: 8Mi
            limits:
              cpu: 20m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
