apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: rhi
  labels:
    hacwa.co.uk/argocd-tenant: rhi
spec:
  owners:
    - name: CapsuleTenantRhi
      kind: Group
      clusterRoles:
        - admin
        - capsule-namespace-deleter

    - name: system:serviceaccount:capsule-argo-system:rhi
      kind: ServiceAccount
      clusterRoles:
        - admin
        - capsule-namespace-deleter

  forceTenantPrefix: true

  namespaceOptions:
    quota: 2

  nodeSelector:
    kubernetes.io/hostname: k8s-worker-03
