apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - certificate.yaml
  - coturn.yaml
  - services.yaml

configMapGenerator:
  - name: matrix-coturn-config
    files:
      - render-coturn.py=tools/render-coturn.py
      - turnserver.conf.template=config/turnserver.conf.template
