apiVersion: v1
kind: Service
metadata:
  name: matrix-element
  namespace: external-services
  labels:
    app.kubernetes.io/name: element
    app.kubernetes.io/part-of: matrix
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: matrix-element
  namespace: external-services
  labels:
    app.kubernetes.io/name: element
    app.kubernetes.io/part-of: matrix
subsets:
  - addresses:
      - ip: 10.0.0.178
    ports:
      - name: http
        port: 8080
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-synapse
  namespace: external-services
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/part-of: matrix
spec:
  ports:
    - name: http
      port: 8008
      protocol: TCP
      targetPort: 8008
---
apiVersion: v1
kind: Endpoints
metadata:
  name: matrix-synapse
  namespace: external-services
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/part-of: matrix
subsets:
  - addresses:
      - ip: 10.0.0.178
    ports:
      - name: http
        port: 8008
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-mas
  namespace: external-services
  labels:
    app.kubernetes.io/name: matrix-authentication-service
    app.kubernetes.io/part-of: matrix
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
---
apiVersion: v1
kind: Endpoints
metadata:
  name: matrix-mas
  namespace: external-services
  labels:
    app.kubernetes.io/name: matrix-authentication-service
    app.kubernetes.io/part-of: matrix
subsets:
  - addresses:
      - ip: 10.0.0.178
    ports:
      - name: http
        port: 8081
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-rtc-auth
  namespace: external-services
  labels:
    app.kubernetes.io/name: matrix-rtc-auth
    app.kubernetes.io/part-of: matrix
spec:
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8082
---
apiVersion: v1
kind: Endpoints
metadata:
  name: matrix-rtc-auth
  namespace: external-services
  labels:
    app.kubernetes.io/name: matrix-rtc-auth
    app.kubernetes.io/part-of: matrix
subsets:
  - addresses:
      - ip: 10.0.0.178
    ports:
      - name: http
        port: 8082
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-livekit-api
  namespace: external-services
  labels:
    app.kubernetes.io/name: livekit
    app.kubernetes.io/part-of: matrix
spec:
  ports:
    - name: http
      port: 7880
      protocol: TCP
      targetPort: 7880
---
apiVersion: v1
kind: Endpoints
metadata:
  name: matrix-livekit-api
  namespace: external-services
  labels:
    app.kubernetes.io/name: livekit
    app.kubernetes.io/part-of: matrix
subsets:
  - addresses:
      - ip: 10.0.0.178
    ports:
      - name: http
        port: 7880
        protocol: TCP
