apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: hacwa
  namespace: elastic-stack
  labels:
    app.kubernetes.io/name: apm-server
    app.kubernetes.io/part-of: elastic-stack
spec:
  version: 9.4.3
  count: 1

  elasticsearchRef:
    name: hacwa

  kibanaRef:
    name: hacwa

  http:
    tls:
      selfSignedCertificate:
        disabled: true

  podTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: apm-server
        app.kubernetes.io/part-of: elastic-stack
    spec:
      containers:
        - name: apm-server
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
