apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jupyterhub-auth
  namespace: jupyterhub
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic

  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: jupyterhub-auth
    creationPolicy: Owner
    deletionPolicy: Retain

    template:
      type: Opaque
      engineVersion: v2
      mergePolicy: Replace
      data:
        password: "{{ .password }}"

  data:
    - secretKey: password
      remoteRef:
        key: hacwa_aws_secrets
        property: jupyterhub-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
