apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-server
  namespace: elastic-stack
  labels:
    app.kubernetes.io/name: fleet-server
    app.kubernetes.io/part-of: elastic-stack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-stack-fleet-server
  labels:
    app.kubernetes.io/name: fleet-server
    app.kubernetes.io/part-of: elastic-stack
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-stack-fleet-server
  labels:
    app.kubernetes.io/name: fleet-server
    app.kubernetes.io/part-of: elastic-stack
subjects:
  - kind: ServiceAccount
    name: fleet-server
    namespace: elastic-stack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elastic-stack-fleet-server
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: elastic-stack
  labels:
    app.kubernetes.io/name: fleet-server
    app.kubernetes.io/part-of: elastic-stack
spec:
  version: 9.4.3
  mode: fleet
  fleetServerEnabled: true
  policyID: eck-fleet-server

  kibanaRef:
    name: hacwa

  elasticsearchRefs:
    - name: hacwa

  http:
    tls:
      selfSignedCertificate:
        disabled: true

  deployment:
    replicas: 1
    strategy:
      type: Recreate
    podTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: fleet-server
          app.kubernetes.io/part-of: elastic-stack
      spec:
        serviceAccountName: fleet-server
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        containers:
          - name: agent
            resources:
              requests:
                cpu: 250m
                memory: 1Gi
              limits:
                cpu: "1"
                memory: 2Gi
