apiVersion: v1
kind: PersistentVolume
metadata:
  name: hacwa-elasticsearch-local-pv
  labels:
    app.kubernetes.io/name: elasticsearch-local
    app.kubernetes.io/part-of: elastic-stack
    hacwa.internal/storage-purpose: elasticsearch
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: elasticsearch-local
  local:
    path: /var/lib/elasticsearch-local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-worker-03
            - key: hacwa.internal/elasticsearch-local
              operator: In
              values:
                - "true"
