apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chartmuseum-data
  namespace: chartmuseum
  labels:
    app.kubernetes.io/name: chartmuseum
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: rook-ceph-block

  resources:
    requests:
      storage: 8Gi
